"use client";

import Link from "next/link";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f]">
      <Header />
      <main className="pt-24 pb-20 px-6">
        <div className="container mx-auto max-w-3xl prose prose-invert prose-slate">
          <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-slate-400 text-sm mb-12">Last updated: {new Date().toLocaleDateString("en-US")}</p>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-300 leading-relaxed">
              By accessing or using the AI Business Factory platform (“Service”), you agree to be bound by these Terms
              of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p className="text-slate-300 leading-relaxed">
              The Service provides AI-powered tools for business creation, including but not limited to logo generation,
              SEO, ads, content, websites, and automation. We reserve the right to modify or discontinue features with
              reasonable notice.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-3">3. Acceptable Use</h2>
            <p className="text-slate-300 leading-relaxed">
              You agree to use the Service only for lawful purposes. You may not use the Service to generate content
              that is illegal, harmful, infringing, or that violates third-party rights. We may suspend or terminate
              access for misuse.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-3">4. Account and Billing</h2>
            <p className="text-slate-300 leading-relaxed">
              You are responsible for maintaining the security of your account. Paid plans are subject to the pricing
              and billing terms presented at signup. Refunds are handled according to our billing policy.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-3">5. Intellectual Property</h2>
            <p className="text-slate-300 leading-relaxed">
              The platform, including its design, code, and branding, is owned by us. Output generated by AI tools
              may be subject to the terms of the underlying AI providers. You retain rights to content you input and
              may use generated output in accordance with your plan and these Terms.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-3">6. Limitation of Liability</h2>
            <p className="text-slate-300 leading-relaxed">
              The Service is provided “as is.” We are not liable for indirect, incidental, or consequential damages,
              or for any loss of data or business arising from use of the Service. Our total liability is limited to
              the amount you paid in the twelve months preceding the claim.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold text-white mb-3">7. Contact</h2>
            <p className="text-slate-300 leading-relaxed">
              For questions about these Terms, contact us at{" "}
              <a href="mailto:shademsarwe2@gmail.com" className="text-violet-400 hover:underline">
                shademsarwe2@gmail.com
              </a>{" "}
              or via the <Link href="/contact" className="text-violet-400 hover:underline">Contact</Link> page.
            </p>
          </section>

          <Link href="/" className="inline-flex text-violet-400 hover:underline mt-8">
            ← Back to Home
          </Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}
